name: Continuous Integration

on:
  push:
    branches: 
      - main
  pull_request:
    branches: [main]

jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: code quality checkout
        run: |
          pip install pylint
          pylint ./pandora-box.py
