name: Continuous Integration

on:
  push:
    branches: 
      - main
  pull_request:
    branches: [main]

jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8

      - name: code quality checkout
        run: |
          pip install pylint
          ls main
          pylint ./main/pandora-box.py

