name: Continuous Integration

on:
  push:
    branches: 
      - master
  pull_request:
    branches: [master]

jobs:

  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Pandora
        run: |
          ./install.sh

      - name: Copy ini file
        run: |
          cp pandora-box.ini.curses pandora-dox.ini

      - name: Start pandora-box
        run: |
          ./pandora-box.py

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: tests/Browser/screenshots

      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: console
          path: tests/Browser/console

